---
  master:
    SONAR_PROJECT_NAME: "cooom-end-master"
    SONAR_PRJECT_KEY: "com.audgfhjwhere:contrghnd-master"
    SONAR_EXCLUSIONS: "gradle/**,build/**,lib/**,*/build/**,deploy/src/main/resources/files/*,packaging/src/main/resources/files/*"
    SONAR_JAVA_BINARIES: "*/build/classes/java/main"
    EMAIL_TO: "sambi.techno@gmail.com"

  Test_jenkins:
    SONAR_PROJECT_NAME: "cm-bd-devvvv"
    SONAR_PRJECT_KEY: "com.automationanywhere:cm-bd-devvvvv"
    SONAR_EXCLUSIONS: "gradle/**,build/**,lib/**,*/build/**,deploy/src/main/resources/files/*,packaging/src/main/resources/files/*"
    SONAR_JAVA_BINARIES: "*/build/classes/java/main"
    EMAIL_TO: "sambi.techno@gmail.com"
